package uz.vv.coretenservice

enum class TenantPlan(val maxUsers: Int) {
    FREE(5),
    BASIC(25),
    PRO(50),
    BUSINESS(150),
    ENTERPRISE(999)
}

enum class Position(val power: Int) {
    INTERN(10),
    EMPLOYEE(20),
    TEAM_LEAD(30),
    MANAGER(40),
    ADMIN(50),
    OWNER(100);
}

enum class TaskPriority {
    LOW,
    MEDIUM_LOW,
    MEDIUM,
    MEDIUM_HIGH,
    HIGH,
    CRITICAL
}
// LOW < MEDIUM_LOW < MEDIUM < MEDIUM_HIGH < HIGH < CRITICAL

enum class TaskActionType {
    CREATED,
    UPDATED,
    TASK_STATE_CHANGED,
    ASSIGNED,
    UNASSIGNED,
    FILE_UPLOADED,
    FILE_DELETED,
    TASK_ALL_FILES_DELETED,
    DELETED
}

enum class FileType {
    DOCUMENT,
    IMAGE,
    VIDEO
}

enum class ErrorCode(val code: Int) {

    USER_NOT_FOUND(101),
    ROLE_NOT_FOUND(102),
    INVALID_PASSWORD(103),
    PASSWORDS_DO_NOT_MATCH(104),
    BAD_CREDENTIALS(105),
    UNAUTHORIZED(106),

    TENANT_NOT_FOUND(201),
    TENANT_ALREADY_EXISTS(202),
    TENANT_SUBSCRIPTION_LIMIT_EXCEEDED(203),

    PROJECT_NOT_FOUND(301),
    PROJECT_ALREADY_EXISTS(302),
    BOARD_NOT_FOUND(303),
    BOARD_ALREADY_EXISTS(304),
    EMPLOYEE_NOT_FOUND(305),

    TASK_NOT_FOUND(401),
    TASK_ALREADY_EXISTS(402),
    TASK_STATE_NOT_FOUND(403),
    TASK_STATE_ALREADY_EXISTS(404),
    TASK_STATE_MISMATCH(405),

    FILE_NOT_FOUND(451),
    FILE_EMPTY(452),
    FILE_TOO_LARGE(453),
    INVALID_FILE_TYPE(454),
    FILE_UPLOAD_FAILED(455),
    FILE_KEY_GENERATION_FAILED(456),

    BAD_REQUEST(900),
    DUPLICATED_RESOURCE(901),
    INTERNAL_SERVER_ERROR(999)
}
