package uz.vv.coretenservice

enum class TenantPlan(val maxUsers: Int) {
    FREE(5),
    BASIC(25),
    PRO(50),
    BUSINESS(150),
    ENTERPRISE(999)
}

enum class Position {
    OWNER,
    ADMIN,
    MANAGER,
    TEAM_LEAD,
    EMPLOYEE,
    INTERN
}


enum class TaskPriority {
    LOW,
    MEDIUM_LOW,
    MEDIUM,
    MEDIUM_HIGH,
    HIGH,
    CRITICAL
}
// LOW < MEDIUM_LOW < MEDIUM < MEDIUM_HIGH < HIGH < CRITICAL

enum class FileType {
    DOCUMENT,
    IMAGE,
    VIDEO
}

enum class ErrorCode(code: Int) {

    USER_NOT_FOUND(101),

    ROLE_NOT_FOUND(101),

    TENANT_NOT_FOUND(204),
    TENANT_ALREADY_EXISTS(205),
    TENANT_SUBSCRIPTION_LIMIT_EXCEEDED(206),

    EMPLOYEE_NOT_FOUND(301),

    PROJECT_NOT_FOUND(304),
    PROJECT_ALREADY_EXISTS(305),

    BOARD_NOT_FOUND(350),
    BOARD_ALREADY_EXISTS(351),

    TASK_NOT_FOUND(404),
    TASK_ALREADY_EXISTS(405),

    TASK_STATE_NOT_FOUND(250),
    TASK_STATE_ALREADY_EXISTS(251),
    TASK_STATE_MISMATCH(252),


    FILE_NOT_FOUND(450),
    FILE_EMPTY(451),
    FILE_TOO_LARGE(452),
    INVALID_FILE_TYPE(453),
    FILE_UPLOAD_FAILED(454),
    FILE_KEY_GENERATION_FAILED(455),


    INVALID_PASSWORD(105),

    PASSWORDS_DO_NOT_MATCH(106),

    DUPLICATED_RECOURSE(101),

    BAD_REQUEST(400),
    BAD_CREDENTIALS(401),

    UNAUTHORIZED(303)
}
